version: "3"
services:
  thing-relay:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=thing-relay
    volumes:
      - ./docker-data/postgresql:/var/lib/postgresql/data